### PR TITLE
Replace axios with NodeJS 18 `fetch()`

### PR DESCRIPTION
**Pull request by datho7561**
`fetch()` works in the browser as well as NodeJS as of NodeJS 18. This PR requires upgrading to NodeJS 18.

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
@fbricon if you have time and think it's okay to drop support for versions before NodeJS 18, could you please take a look at this PR?

**Comment by datho7561** [comment]
Okay, thanks!

**Comment by datho7561** [comment]
@fbricon if you have some time could you please take a look at this PR? (no rush though)

**Review by rgrunber — APPROVED** [review]
I tried this out (with npm link) and it seems to be working well.

Unrelated to this PR, but I did run into conflicts between the @types/vscode defined in the extension I was testing (vscode-java) and vscode-redhat-telemetry when used with the linking approach. I don't remember running into this before when testing like that.

**Comment by rgrunber** [comment]
If this gets updated I won't have to update https://github.com/redhat-developer/vscode-java/pull/3755 :stuck_out_tongue_winking_eye:

**Comment by fbricon** [comment]
thx @datho7561

**Pull request merged**
